onlydustxyz/starklings

contracts/core/space.cairo
tests/test_space.py

Still need to adjust @tdelabro protostar test but I'll do it in a next PR.

Refactor grid storage

---

contracts/core/space.cairo
contracts/interfaces/ispace.cairo
contracts/models/common.cairo
tests/test_space.cairo
tests/test_space.py

Do not put a `Vector2` position in the cells given by the `get_grid_state` method of the `Space` contract.

Simplify cells

---

contracts/interfaces/itournament.cairo
contracts/tournament/Tournament.cairo
tests/tournament/test_tournament.cairo

Only 1 ship per player.
A ship cannot be registered by multiple players.

feat(registration): players can register their ship

---

.github/workflows/formatting.yml
.github/workflows/linting.yml
requirements.txt
tests/fixtures.py
tests/helpers.py
tests/test_advanced_ex00.py
tests/test_advanced_ex01.py
tests/test_beginner_ex00.py
tests/test_beginner_ex01.py
tests/test_beginner_ex02.py
tests/test_beginner_ex03.py
tests/test_beginner_ex04.py
tests/test_multiple_turns.py
tests/test_space.py
tests/test_tournament.py
tests/utils.py

Add a code format checker in the CI.
Renamed linting to formatting since only code format is checked right now, another PR will come with a real linter.

Python formatting

---

.gitignore
poetry.lock
pyproject.toml
pytest.ini
starklings.py
starklings.spec

Add binary building scripts

---

.github/workflows/build_binaries.yml
deploy.py
install.sh
pyproject.toml

Add a Python script to create a release tag, and add a Github workflow to catch this tag when it reaches the `main` branch to build and publish the binaries.

Deployment

---

.github/workflows/formatting.yml
.github/workflows/test.yml
poetry.lock
pyproject.toml
src/__init__.py
src/cli.py
src/utils/starklings_directory.py
src/utils/starklings_directory_test.py
starklings.py

Add the same CLI as protostar, with a single command for now, printing the version.

Command line interface

---

.github/workflows/test.yml
README.md
poetry.lock
protostar.toml
pyproject.toml
src/exercise_runner/runner.py
src/exercise_runner/runner_test.py
src/protostar.py
src/utils/starklings_directory.py
starklings.py
tests/test.cairo
tests/test_failure.cairo
tests/test_invalid.cairo

Closes #77 
Protostar is considered as external, I did not manage to make use of the python API.
We'll wait for the package to be published on Pypi to make direct python use of it.

Exercise testing

---

.github/workflows/formatting.yml
contracts/advanced/ex00.cairo
contracts/advanced/ex01.cairo
contracts/beginner/ex00.cairo
contracts/beginner/ex01.cairo
contracts/beginner/ex02.cairo
contracts/beginner/ex03.cairo
contracts/beginner/ex04.cairo
poetry.lock
pyproject.toml
src/utils/starklings_directory.py

Set a specific version of the cairo-lang package to be consistent with the formatting rules installed locally and checked in the CI.

Pin cairo lang version

---

src/exercise_checker/checker.py

Closes #88 
Use asyncio with subprocess to keep track of the currently running processes.

Check for already running checks before spawning a new one

---

README.md
src/exercise_checker/checker.py
src/exercise_checker/checker_test.py
src/runner.py
starklings.py

Use user repository to check exercises

---

src/prompt.py
src/runner.py

Closes #92 
This improves the console prints, next step is to clear the previous outputs but this is not trivial.

Improve console outputs

---

src/cli.py
src/exercise_checker/checker.py
src/exercise_checker/checker_test.py
src/runner.py
tests/test_missing.cairo

Compatibility with protostar 0.2.0

---

.patches/syntax/syntax01.cairo.patch
.patches/syntax/syntax02.cairo.patch
.patches/syntax/syntax03.cairo.patch
.patches/syntax/syntax04.cairo.patch
.patches/syntax/syntax05.cairo.patch
exercises/syntax/README.md
exercises/syntax/syntax01.cairo
exercises/syntax/syntax02.cairo
exercises/syntax/syntax03.cairo
exercises/syntax/syntax04.cairo
exercises/syntax/syntax05.cairo
src/constants.py

Create an exercise track to teach the basic syntax of Starknet contracts.
Closes #102

Syntax track

---

.github/workflows/test.yml
README.md
poetry.lock
pyproject.toml
src/cli.py
src/exercise_checker/checker.py
src/exercise_checker/checker_test.py
src/protostar.py
src/runner.py
src/utils/starklings_directory.py
src/utils/starklings_directory_test.py

Closes #109.
Had to publish myself a version of the package that can be used here, since the Protostar team [does not really agree](https://github.com/software-mansion/protostar/issues/264) on publishing their package.

Protostar python functions

---

.patches/recursions/array01.cairo.patch
.patches/recursions/array02.cairo.patch
.patches/recursions/recursion01.cairo.patch
exercises/recursions/README.md
exercises/recursions/array01.cairo
exercises/recursions/array02.cairo
exercises/recursions/recursion01.cairo
src/constants.py

Recursions

---

CONTRIBUTING.md
README.md

Separate contribution instructions

---

.patches/implicit_arguments/implicit_arguments01.cairo.patch
.patches/implicit_arguments/implicit_arguments02.cairo.patch
.patches/implicit_arguments/implicit_arguments03.cairo.patch
exercises/implicit_arguments/README.md
exercises/implicit_arguments/implicit_arguments01.cairo
exercises/implicit_arguments/implicit_arguments02.cairo
exercises/implicit_arguments/implicit_arguments03.cairo
src/constants.py

Implicit arguments

---

.patches/beginner/ex00.cairo.patch
.patches/beginner/ex01.cairo.patch
exercises/beginner/ex00.cairo
exercises/beginner/ex01.cairo

#127 Fix outdated documentation links

fix documentation broken links

---

src/prompt.py
src/runner.py

The CLI must run in the repository

---

src/cli.py

Message tracing was crashing the solution display function

---

.patches/strings/strings00.cairo.patch
exercises/strings/README.md
exercises/strings/strings00.cairo
src/constants.py

Educational content: add some exercises about short strings

---

.patches/recursions/array03.cairo.patch
exercises/recursions/array03.cairo
src/constants.py

Educational content: exercise on array traversal

---

src/cli.py
src/solution.py
src/solution_test.py

Feat: stash user changes before displaying a solution

---

.github/workflows/deployment.yml
README.md

Feat: stable branch

---

.patches/recursions/struct01.cairo.patch
exercises/recursions/struct01.cairo
src/constants.py

Shows how to be (kind of) generic with structs.

feat(exercises): add recursions/struct01.cairo

---

.patches/hints/hints01.cairo.patch
exercises/hints/README.md
exercises/hints/hints01.cairo
src/constants.py

Educational content: follow-up exercise on hints.

---

.github/workflows/formatting.yml
.github/workflows/linting.yml
.github/workflows/test.yml

See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target and https://www.youtube.com/watch?v=Ww5gjAm-2GY

Feat: configure GH actions to run on forks PRs

---

src/runner.py

Push an event to sentry when an exercises tests pass

feat(sentry): capture exercise solved

---

src/cli.py
src/console.py
src/prompt.py

Feat: improve console output

---

src/prompt.py
src/runner.py
src/runner_test.py
tests/exercises/test_end_of_exercise_messages/with_next_exercises/syntax01.cairo
tests/exercises/test_end_of_exercise_messages/with_next_exercises/syntax02.cairo
tests/exercises/test_end_of_exercise_messages/without_next_exercises/syntax01.cairo
tests/exercises/test_end_of_exercise_messages/without_next_exercises/syntax02.cairo

Hi! I added : 
- a new prompt function in src/prompt.py
- a new unit test file for src/runner.py
- new cairo files inside ./tests for ./src/runner_test.py

fix #191 - Fix end of exercises message

---

.gitignore
poetry.lock
pyproject.toml
src/cli.py
src/config.py
src/database.py
src/prompt.py
src/user/access_token.py
src/user/login.py
src/user/login_test.py
starklings.py

Feat: login with Github

---

.github/workflows/deployment.yml

Update obsolete MacOs version in build CI from `macOS-10.15` to `macOS-11`

fix(ci): update macos os version
